version: '3.8'

services:
  mysql:
    image: mysql:latest
    container_name: meu-banco
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: meu_banco
      MYSQL_PASSWORD: root
    ports:
      - "3306:3306"
    volumes:
      - mysql-data:/var/lib/mysql
  redis:
    image: redis:latest
    container_name: meu-redis
    ports:
      - "6379:6379"
volumes:
  mysql-data:
